default:
    adapter: mysql2
    database: cat_rescue
    username: admin1
    password: admin
    host: localhost
development:
    adapter: mysql2
    database: cat_rescue
    username: admin1
    password: admin
    host: localhost
production:
    adapter: mysql2
    database: cat_rescue
    username: admin1
    password: admin
    host: localhost